version: 2.1

aliases:
  - &working_directory ~/circleci-executors

executors:
  rust-docker:
    docker:
      - image: cimg/rust:1.87.0
    working_directory: *working_directory

jobs:
  build:
    executor: rust-docker
    steps:
      - checkout
      - run: cargo --version

workflows:
  build:
    jobs:
      - build
